import Head from "next/head";
import Hero from "./Hero";
import About from "./About";
import Footer from "./Footer";
import Services from "./Services";
import Work from "./Work";
import NavBar from "./Navbar";
// import SideDrawer from "../components/SideDrawer";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Vaibhav Sindal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      {/* <SideDrawer /> */}
      <Hero />
      {<About />}
      {<Services />}
      {<Work />}
      {<Footer />}
    </div>
  );
}
